---
abstract: 'Provides assertion macros for XS modules'
author:
  - 'Goro Fuji (gfx) <gfuji(at)cpan.org>'
build_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.42
  ExtUtils::ParseXS: 2.2
  Test::More: 0.42
  XSLoader: 0.08
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: XS::Assert
name: XS-Assert
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  perl: 5.00503
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/gfx/P5-XS-Assert.git
version: 0.002
